link_rails_tut: "https://www.railstutorial.org/"
#contact
rails: https://www.railstutorial.org/contact
vi: vi
en: en
link_rails_tut: http://www.railstutorial.org/
help: http://www.railstutorial.org/help
book: http://www.railstutorial.org/book
ct: http://www.railstutorial.org/contact
ror: http://www.railstutorial.org/
ss: http://screencasts.railstutorial.org/
ruby: http://rybyonrails.org/
news: http://news.railstutorial.org/
michaelhartl: http://www.michaelhartl.com/
